---
- name: Remove the user 'awsuser'
  hosts: all
  become: yes
 
  tasks:

      - name: Remove the user 'awsuser'
        user:
          name: awsuser
          state: absent
          remove: yes